apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xd6i4av8x-nodejs
  janus-idp.io/tekton: xd6i4av8x-nodejs
  backstage.io/kubernetes-id: xd6i4av8x-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xd6i4av8x-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
