apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xd6i4av8x-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xd6i4av8x-nodejs 
  name: xd6i4av8x-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: xd6i4av8x-nodejs 
